// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoboNQNS1F4JGZgBEpP8waqiOcMD-IIHE',
    appId: '1:1010883932518:web:2f11505d196f572c3798a7',
    messagingSenderId: '1010883932518',
    projectId: 'mnx-attendance-app',
    authDomain: 'mnx-attendance-app.firebaseapp.com',
    storageBucket: 'mnx-attendance-app.firebasestorage.app',
    measurementId: 'G-JD442S9PP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQuJWJ6JNRMkAfBfecTdFSlpOD39emll0',
    appId: '1:1010883932518:android:5e5bb946f5e55fc63798a7',
    messagingSenderId: '1010883932518',
    projectId: 'mnx-attendance-app',
    storageBucket: 'mnx-attendance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZsrUfTE1aP7Vfln-T2asu373z4dHCM14',
    appId: '1:1010883932518:ios:4a973ceaec31ac693798a7',
    messagingSenderId: '1010883932518',
    projectId: 'mnx-attendance-app',
    storageBucket: 'mnx-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.mnxAttendanceApp',
  );
}
